# Generated by Django 5.0.4 on 2024-05-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_alter_client_phone_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
