# Generated by Django 5.0.4 on 2024-05-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_alter_employee_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_until',
            field=models.DateField(),
        ),
    ]
