# Generated by Django 5.0.4 on 2024-05-11 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_alter_employee_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='busy_until',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
