# Generated by Django 5.0.4 on 2024-05-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0009_alter_promocode_code_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='main/images'),
        ),
    ]
