# Generated by Django 5.0.4 on 2024-05-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0010_alter_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='client_name',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
